Rust 中的错误处理比想象中的还要优雅，但无论语言提供了多么优雅的处理方式，首先还是要理解才能合理的运用它。

Rust 中有两类错误处理：`panic` 和 `Result`。普通错误用 `Result` 来处理，它通常表示由外部程序引发的错误。而 `panic` 针对的是另一种错误，即那种永远不应该发生的错误。
## panic

当遇到以下问题的时候，就可以断定程序自身存在 bug，故而会引发 `panic`：

- 数组访问越界；
- 整数除以 0；
- 在恰好为 `Err` 的 `Result` 上调用 `.expect()`；
- 断言失败。

> 在 `panic` 时 Rust 的默认行为是展开调用栈。

`panic` 是基于线程的。一个线程 `panic` 时，其他县城可以继续运行。
## Result

Rust 中没有异常。相反，函数执行失败时会返回一个 `Result` 作为代替：

```rust
fn get_rua() -> Result<RUA, io::Error>
```

## Axum 中的错误处理

Axum 是一个优秀的 HTTP server 框架，它基于 tokio、hyper 和 tower 构建。不仅有优秀的异步性能，还有通用的 HTTP 标准。

对于任何一个应用程序的错误处理都是必不可少的，Axum 自然也是如此。

在 axum 仓库中的 `exmaples` 中，有一个 [error-handling](https://github.com/tokio-rs/axum/blob/9ebd105d0410dcb8a4133374c32415b5a6950371/examples/error-handling/src/main.rs) 的示例。

